#+TITLE: Poincaré Waves Incident on a Corrugated Shelf (PWICS) MITgcm Setup

* Setup

1) Clone this repository.
2) Edit ~setup/gendata_params.m~ to modify the incidence angle and topographic wavenumber range.
3) Modify ~mitgcm_root~ and ~buildopts~ in ~setup/build_all.sh~ to point to your MITgcm folder (cloned from GitHub) and your machine's build options file.
4) Use ~description.txt~ to make notes for later reference.
5) Modify ~setup/gendata_params.m~ to define topographic wavenumber(s) and incidence angle(s).
6) Run ~setup/gendata_all.m~ (from the ~setup~ directory). This will create a directory for each run containing input files and code.
7) Run ~setup/build_all.sh~ (from the ~setup~ directory). This creates an executable for each incidence angle.
8) ~run_all.sh~ can be modified and used to run a list of simulations, e.g.
   #+BEGIN_SRC shell
   cd setup
   nohup ./run_all run_list > log.txt &
   #+END_SRC

9) Repeat steps 5 and 7, but using ~setup/gendata_all_pickup.m~ to resume from the latest pickup file.



** Working in limited-connectivity settings without git

After step 1) above, copy this directory to the remote server, e.g.

#+BEGIN_SRC shell
rsync -av MITgcm-PWICS/ server:~/MITgcm/simulations/PWICS_01
#+END_SRC

Then follow the rest of the steps, but on the server. If you've generated input locally, you can either run ~cleanup.sh~ from the setup directory, or re-clone this repository to a new location for a fresh start.
